import type { CombatCard } from "@sts2/shared/types/game-state";
import { createClient } from "@sts2/shared/supabase/client";

const VALID_CARDS_KEY = "sts2-valid-cards";

let validCardNames: Set<string> | null = null;
let loading = false;

/**
 * Known status/curse cards that enemies add to the player's deck.
 * Used as a synchronous fallback before Supabase data loads.
 */
const KNOWN_STATUS = new Set([
  "wound", "burn", "dazed", "slimed", "void", "debris",
  "beckon", "disintegration", "frantic escape", "infection",
  "mind rot", "sloth", "soot", "toxic", "waste away",
]);

/**
 * Load valid card names from localStorage (sync) and trigger
 * an async refresh from Supabase. Call once at app startup.
 */
export function initValidCardNames(): void {
  if (validCardNames || loading) return;

  // Sync load from localStorage
  if (typeof window !== "undefined") {
    try {
      const cached = localStorage.getItem(VALID_CARDS_KEY);
      if (cached) {
        validCardNames = new Set(JSON.parse(cached) as string[]);
        return;
      }
    } catch {
      // Fall through to async fetch
    }
  }

  // Async load from Supabase
  loading = true;
  const supabase = createClient();
  supabase
    .from("cards")
    .select("name, type")
    .neq("type", "Status")
    .then(({ data }) => {
      const names = new Set(
        (data ?? []).map((c) => c.name.toLowerCase())
      );
      // Add upgraded variants
      for (const name of [...names]) {
        names.add(`${name}+`);
      }
      validCardNames = names;
      loading = false;

      if (typeof window !== "undefined") {
        try {
          localStorage.setItem(VALID_CARDS_KEY, JSON.stringify([...names]));
        } catch {
          // Non-critical
        }
      }
    });
}

/**
 * Returns true if the card is a real player card (not a status/curse
 * generated by enemies during combat).
 */
export function isPlayerCard(card: CombatCard): boolean {
  if (validCardNames) {
    return validCardNames.has(card.name.toLowerCase());
  }
  // Fallback: reject known status cards
  return !KNOWN_STATUS.has(card.name.toLowerCase());
}

/**
 * Filter an array of combat cards to only include real player cards.
 */
export function filterPlayerCards(cards: CombatCard[]): CombatCard[] {
  return cards.filter(isPlayerCard);
}
