import type { CombatCard } from "@sts2/shared/types/game-state";
import { createClient } from "@sts2/shared/supabase/client";

let validCardNames: Set<string> | null = null;
let loading = false;

/**
 * Known status/curse cards that enemies add to the player's deck.
 * Used as a synchronous fallback before Supabase data loads.
 */
const KNOWN_STATUS = new Set([
  "wound", "burn", "dazed", "slimed", "void", "debris",
  "beckon", "disintegration", "frantic escape", "infection",
  "mind rot", "sloth", "soot", "toxic", "waste away",
]);

/**
 * Load valid card names from Supabase into in-memory cache.
 * Call once at app startup. Uses KNOWN_STATUS as fallback
 * until the async load completes.
 */
export function initValidCardNames(): void {
  if (validCardNames || loading) return;

  loading = true;
  const supabase = createClient();
  supabase
    .from("cards")
    .select("name, type")
    .neq("type", "Status")
    .then(({ data }) => {
      const names = new Set(
        (data ?? []).map((c) => c.name.toLowerCase())
      );
      for (const name of [...names]) {
        names.add(`${name}+`);
      }
      validCardNames = names;
      loading = false;
    });
}

/**
 * Returns true if the card is a real player card (not a status/curse
 * generated by enemies during combat).
 */
export function isPlayerCard(card: CombatCard): boolean {
  if (validCardNames) {
    return validCardNames.has(card.name.toLowerCase());
  }
  return !KNOWN_STATUS.has(card.name.toLowerCase());
}

/**
 * Filter an array of combat cards to only include real player cards.
 */
export function filterPlayerCards(cards: CombatCard[]): CombatCard[] {
  return cards.filter(isPlayerCard);
}
